### ISSUE TITLE
Can't build...

### ISSUE THREAD

**Issue by zquestz** [chevil/raop2_play#1]
So, the docs say to ./configure, but there is no configure script. Make is failing for me as well with the following:

gcc -Wall -c raop_client.c -o raop_client.o
raop_client.c:400:10: error: conflicting types for ‘calculate_timestamp’
In file included from raop_client.c:39:0:
raop_client.h:52:20: note: previous declaration of ‘calculate_timestamp’ was here
make: *** [raop_client.o] Error 1

Any suggestions?

**Comment by LinusU** [comment]
That error should be fixed by #3
